language: node_js
os: linux
dist: focal
node_js: 18

cache:
  npm: false
  directories:
    - $HOME/.yarn/berry/cache
    - $HOME/.cargo
    - $HOME/.pkg-cache

git:
  # required to enable symlinks on windows
  symlinks: true

install:
  - yarn && yarn run build

jobs:
  include:
    # Linux testing is performed by GitHub Actions
    - os: linux
      node_js: 18
      script:
        - yarn run smoketest

    - os: windows
      node_js: 18
      env:
        - YARN_GPG=no
      script: yarn test

    - stage: deploy
      if: branch = main
      node_js: 18
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y qemu-user-static
      install:
        - yarn
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile default -y
        - source "$HOME/.cargo/env"
      script: |
        ./bin/presign \
        && yarn build \
        && yarn run semantic-release \
        && yarn run chromatic --auto-accept-changes
