language: node_js
os: linux
dist: xenial
node_js: [14]

cache:
  npm: false
  directories:
  - ~/.npm
  - ~/AppData/Roaming/npm-cache
  
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

if: tag IS present OR commit_message !~ /^chore(release)/

install:
- npm cache verify
- yarn
- yarn run build

if: tag !~ @appland/.+-v\d\.\d\.\d

jobs:
  include:
    - stage: test
      script: yarn run ci

    - stage: test-windows
      os: windows
      env:
        - YARN_GPG=no
      script: yarn workspace @appland/appmap test --runTestsByPath tests/unit/agentInstall/gradleInstaller.spec.ts
      
    - stage: deploy
      if: branch != main
      script: yarn run chromatic

    - stage: deploy
      if: branch = main
      script: |
        yarn run chromatic --auto-accept-changes \
        && yarn run semantic-release -e semantic-release-monorepo
