language: node_js
os: linux
dist: focal
node_js: [14, 16, 18]

cache: false

git:
  # required to enable symlinks on windows
  symlinks: true

install:
  - yarn && yarn run build
script: yarn run ci

jobs:
  include:
    - stage: test
      os: windows
      env:
        - YARN_GPG=no
      script: yarn test

    - stage: deploy
      if: branch != main
      script: yarn run chromatic

    - stage: deploy
      if: branch = main
      script: |
        yarn run chromatic --auto-accept-changes \
        && yarn run build-native \
        && yarn run semantic-release
