enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  '@storybook/builder-webpack5@6.5.14':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/manager-webpack5@6.5.14':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/addon-docs@6.5.14':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
      webpack:
        optional: true
  '@storybook/mdx1-csf@0.0.1':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  '@storybook/vue@6.5.14':
    peerDependenciesMeta:
      typescript:
        optional: true
  '@babel/plugin-syntax-jsx@7.16.7':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  '@vue/cli-plugin-unit-jest@4.5.15':
    peerDependencies:
      vue: '^2'
      vue-template-compiler: '^2'
  'rollup-plugin-sass@1.2.10':
    peerDependencies:
      rollup: '^1.20.0||^2.0.0'
  'rollup-plugin-vue@5.1.9':
    peerDependencies:
      postcss: '>=6.0'
  'swagger-parser@10.0.3':
    peerDependencies:
      openapi-types: '>=7'
  'openapi-diff@0.23.6':
    peerDependencies:
      openapi-types: '>=7'
  'vue-docgen-api@4.56.0':
    peerDependencies:
      vue: '>=2'
