enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  '@storybook/builder-webpack5@6.5.14':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/manager-webpack5@6.5.14':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/addon-docs@6.5.14':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
      webpack:
        optional: true
  '@storybook/mdx1-csf@0.0.1':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  '@storybook/vue@6.5.14':
    peerDependenciesMeta:
      typescript:
        optional: true
