name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  yarn_install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

  test_components:
    runs-on: ubuntu-latest

    needs: [yarn_install]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Build
        run: |
          yarn lint && yarn build

      - name: Test
        run: |
          cd packages/components
          yarn test

  test_cli:
    runs-on: ubuntu-latest

    needs: [yarn_install]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Build
        run: |
          yarn lint && yarn build

      - name: Test
        run: |
          cd packages/cli
          yarn test

      - name: AppMap
        run: |
          cd packages/cli
          npx appmap-node yarn test || true

  test_all:
    runs-on: ubuntu-latest
    needs: [test_components, test_cli]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Build
        run: |
          yarn && yarn build

      - name: Test
        run: |
          yarn workspaces foreach --exclude root --exclude packages/components --exclude packages/cli run test
